Add support for ruby 3 versions
lessonly/scim_rails pull request #65
Opened 2023-07-06 08:14 UTC by pragya-sriharsh

## Why?

I am working on ruby & rails upgrade stories. As this branch is restricted to ruby 2.4 version so i have modified to support > ruby 3 versions. Initially i have modified for ruby 3.2.2 version but lessonly's some gems have some dependencies on ruby 3.0.0 so i degraded from 3.2.2 to 3.0.0. But this changes is working as expected for ruby 3.0.x too. 

## What?

Modified files to support ruby 3 version:
- changes in .ruby-version
- changes in .gemspec  that restricts previously to 2.4 ruby version
- changes in .tool-versions
- travis.yml

## Caveats
I don't know where all this gem is being used. Currently i am using it along with lessonly with this feature branch. 

## Testing Notes
NA

## Merge Instructions

Please **DO NOT** squash my commits when merging

2023-07-12 20:18 UTC, JJGayso requested changes

2023-07-12 20:18 UTC, JJGayso commented on .ruby-version
> +3.2.2
Was this meant to be brought to 3.0.0 based on your PR comment?

2023-07-13 13:32 UTC, JJGayso submitted a review, later dismissed

2023-07-14 08:59 UTC, pragya-sriharsh commented
A small change in meta to indicate ruby versions >=2.4 and <=3.2

2023-07-14 12:01 UTC, nayan-guptaS submitted a review, later dismissed

2023-07-14 15:07 UTC, unixmonkey commented
Why cap the upper bound at all? I would bet it works fine with Ruby 3.3 and up.

2023-07-14 15:11 UTC, pragya-sriharsh commented
I just thought to mention that otherwise >=2.4 was enough.  Should i remove ?

2023-07-14 15:22 UTC, unixmonkey commented
If you leave this library locked to `<=3.2`, then around the end of the year, when Ruby 3.3 final is released, then this gem will need another release, and potentially block people from upgrading to 3.3 if they use this as a dependency. Maybe for years until someone with commit access finally gets around to it, like has happened already.

In the small case that maybe something with Ruby 3.3 or higher does somehow "break" with this gem, I'm sure you'll hear about it, and then can work on an actual code fix, instead of re-pinning an upper bound, and re-releasing the gem every time a new Ruby is released.

Yes, I would recommend removing the upper bound entirely, at least until you know for sure a version won't work with it.

2023-07-14 18:13 UTC, pragya-sriharsh commented
Okay got it @unixmonkey .  Reverting this commit.

2023-07-14 19:06 UTC, nayan-guptaS approved these changes

2023-07-17 04:11 UTC, prasadb05 approved these changes
QA testing is not required to test this PR so approving it as discussed with @JJGayso 
<img width="1337" alt="MicrosoftTeams-image (14)" src="https://github.com/lessonly/scim_rails/assets/121278257/cd6e422f-4021-4077-bce9-d4005440ee8b">

2023-07-21 13:09 UTC, merged